spring:
  application:
    name: Suhbatchi

  datasource:
    username: postgres
    url: jdbc:postgresql://shortline.proxy.rlwy.net:12259/railway
    password: UlEpPrnqbAaHYSfQLVshlxHICNIGeWsH
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update


otp:
  base-url: https://notify.eskiz.uz/api