spring:
  application:
    name: Suhbatchi

  datasource:
    url: jdbc:postgresql://shortline.proxy.rlwy.net:12259/railway
    username: postgres
    password: UlEpPrnqbAaHYSfQLVshlxHICNIGeWsH
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update


otp:
  base-url: https://notify.eskiz.uz/api

tax:
  base-url: https://my3.soliq.uz/api
springdoc:
  swagger-ui:
    path: /swagger-ui.html
